iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  compilation_workers: 3
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties: {}
    - name: access_z2
      cloud_properties: {}
    - name: access_z3
      cloud_properties: {}
    - name: brain_z1
      cloud_properties: {}
    - name: brain_z2
      cloud_properties: {}
    - name: brain_z3
      cloud_properties: {}
    - name: cc_bridge_z1
      cloud_properties: {}
    - name: cc_bridge_z2
      cloud_properties: {}
    - name: cc_bridge_z3
      cloud_properties: {}
    - name: cell_z1
      cloud_properties: {}
    - name: cell_z2
      cloud_properties: {}
    - name: cell_z3
      cloud_properties: {}
    - name: colocated_z1
      cloud_properties: {}
    - name: colocated_z2
      cloud_properties: {}
    - name: colocated_z3
      cloud_properties: {}
    - name: database_z1
      cloud_properties: {}
    - name: database_z2
      cloud_properties: {}
    - name: database_z3
      cloud_properties: {}
    - name: route_emitter_z1
      cloud_properties: {}
    - name: route_emitter_z2
      cloud_properties: {}
    - name: route_emitter_z3
      cloud_properties: {}
    - name: errand
      cloud_properties: {}

  subnet_configs:
    - name: diego1
      type: manual
      subnets:
      - cloud_properties: {}
        gateway: 10.244.16.1
        range: 10.244.16.0/24
        reserved:
        - 10.244.16.1
        static: []
    - name: diego2
      type: manual
      subnets:
      - cloud_properties: {}
        gateway: 10.244.18.1
        range: 10.244.18.0/24
        reserved:
        - 10.244.18.1
        static: []
    - name: diego3
      type: manual
      subnets:
      - cloud_properties: {}
        gateway: 10.244.20.1
        range: 10.244.20.0/24
        reserved:
        - 10.244.20.1
        static: []
    - name: diego-benchmarks
      type: manual
      subnets:
      - cloud_properties: {}
        gateway: 10.244.26.1
        range: 10.244.26.0/30
        reserved:
        - 10.244.26.1
        static: []
    - name: diego-vizzini
      type: manual
      subnets:
      - cloud_properties: {}
        gateway: 10.244.28.1
        range: 10.244.28.0/30
        reserved:
        - 10.244.28.1
        static: []
